import { ConceptItem } from '../types/game';

export const GAME_CONCEPTS: ConceptItem[] = [
  // Doğa & Hava Durumu
  {
    id: 'sun',
    name: 'Güneş',
    clue: 'Gündüz gökyüzünde parlar, etrafı ısıtır ve aydınlatır',
    category: 'Hava Durumu',
    icon: 'sunny',
    iconType: 'Ionicons',
    color: '#F59E0B',
    accentColor: '#FEF3C7',
  },
  {
    id: 'rain',
    name: 'Yağmur',
    clue: 'Bulutlardan damla damla yere düşen serin su',
    category: 'Hava Durumu',
    icon: 'rainy',
    iconType: 'Ionicons',
    color: '#0EA5E9',
    accentColor: '#E0F2FE',
  },
  {
    id: 'snow',
    name: 'Kar Tanesi',
    clue: 'Kışın gökten süzülen beyaz ve soğuk kristaller',
    category: 'Hava Durumu',
    icon: 'snow',
    iconType: 'Ionicons',
    color: '#38BDF8',
    accentColor: '#F0F9FF',
  },
  {
    id: 'thunder',
    name: 'Şimşek',
    clue: 'Fırtınalı havalarda göğü aniden aydınlatan elektrik',
    category: 'Hava Durumu',
    icon: 'flash',
    iconType: 'Ionicons',
    color: '#EAB308',
    accentColor: '#FEF9C3',
  },
  {
    id: 'umbrella',
    name: 'Şemsiye',
    clue: 'Yağmurlu günlerde açarak ıslanmaktan korunduğumuz eşya',
    category: 'Eşyalar',
    icon: 'umbrella',
    iconType: 'Ionicons',
    color: '#8B5CF6',
    accentColor: '#EDE9FE',
  },
  {
    id: 'tree',
    name: 'Ağaç',
    clue: 'Kökleri toprakta, dallarında yapraklar olan yeşil doğa dostu',
    category: 'Doğa',
    icon: 'tree',
    iconType: 'MaterialCommunityIcons',
    color: '#10B981',
    accentColor: '#D1FAE5',
  },
  {
    id: 'flower',
    name: 'Çiçek',
    clue: 'İlkbaharda rengarenk açan ve güzel kokan bitki',
    category: 'Doğa',
    icon: 'flower',
    iconType: 'MaterialCommunityIcons',
    color: '#EC4899',
    accentColor: '#FCE7F3',
  },
  {
    id: 'fire',
    name: 'Ateş',
    clue: 'Odunları yakınca çıkan, sıcak ve alev alev parlayan güç',
    category: 'Doğa',
    icon: 'flame',
    iconType: 'Ionicons',
    color: '#F97316',
    accentColor: '#FFEDD5',
  },
  {
    id: 'water',
    name: 'Su Damlası',
    clue: 'Susayınca içtiğimiz, yaşam kaynağı berrak sıvı',
    category: 'Doğa',
    icon: 'water',
    iconType: 'Ionicons',
    color: '#06B6D4',
    accentColor: '#CFFAFE',
  },

  // Meyve & Yiyecek
  {
    id: 'apple',
    name: 'Elma',
    clue: 'Ağaçta yetişen, kırmızı veya yeşil sulu kütür meyve',
    category: 'Meyve & Yiyecek',
    icon: 'food-apple',
    iconType: 'MaterialCommunityIcons',
    color: '#EF4444',
    accentColor: '#FEE2E2',
  },
  {
    id: 'pizza',
    name: 'Pizza',
    clue: 'Üzerinde peynir, sos ve malzemeler olan üçgen dilimli lezzet',
    category: 'Meyve & Yiyecek',
    icon: 'pizza',
    iconType: 'Ionicons',
    color: '#F59E0B',
    accentColor: '#FEF3C7',
  },
  {
    id: 'icecream',
    name: 'Dondurma',
    clue: 'Yazın külaha konan, soğuk ve tatlı serinletici lezzet',
    category: 'Meyve & Yiyecek',
    icon: 'ice-cream',
    iconType: 'Ionicons',
    color: '#EC4899',
    accentColor: '#FCE7F3',
  },
  {
    id: 'coffee',
    name: 'Kahve',
    clue: 'Sabahları uyanmak için kupada içilen sıcak içecek',
    category: 'Meyve & Yiyecek',
    icon: 'cafe',
    iconType: 'Ionicons',
    color: '#78350F',
    accentColor: '#FEF3C7',
  },
  {
    id: 'cake',
    name: 'Doğum Günü Pastası',
    clue: 'Üzerine mum dikilip üflenen kutlama tatlısı',
    category: 'Meyve & Yiyecek',
    icon: 'cake-variant',
    iconType: 'MaterialCommunityIcons',
    color: '#D946EF',
    accentColor: '#FAE8FF',
  },

  // Hayvanlar
  {
    id: 'cat',
    name: 'Kedi',
    clue: 'Miyavlayan, yün yumağıyla oynayan sevimli evcil dost',
    category: 'Hayvanlar',
    icon: 'cat',
    iconType: 'MaterialCommunityIcons',
    color: '#F97316',
    accentColor: '#FFEDD5',
  },
  {
    id: 'dog',
    name: 'Köpek',
    clue: 'Kuyruğunu sallayan, sadık ve havlayan neşeli dost',
    category: 'Hayvanlar',
    icon: 'dog',
    iconType: 'MaterialCommunityIcons',
    color: '#B45309',
    accentColor: '#FEF3C7',
  },
  {
    id: 'bird',
    name: 'Kuş',
    clue: 'Kanatlarıyla göklerde süzülen ve cik cik öten canlı',
    category: 'Hayvanlar',
    icon: 'bird',
    iconType: 'MaterialCommunityIcons',
    color: '#0EA5E9',
    accentColor: '#E0F2FE',
  },
  {
    id: 'fish',
    name: 'Balık',
    clue: 'Yüzgeçleriyle sularda yüzen ve solungaçlarıyla nefes alan canlı',
    category: 'Hayvanlar',
    icon: 'fish',
    iconType: 'Ionicons',
    color: '#06B6D4',
    accentColor: '#CFFAFE',
  },
  {
    id: 'bee',
    name: 'Arı',
    clue: 'Çiçekleri dolaşıp peteklere tatlı bal yapan kanatlı dost',
    category: 'Hayvanlar',
    icon: 'bee',
    iconType: 'MaterialCommunityIcons',
    color: '#EAB308',
    accentColor: '#FEF9C3',
  },

  // Araçlar
  {
    id: 'car',
    name: 'Araba',
    clue: 'Dört tekeri olan ve karayolunda yolcu taşıyan taşıt',
    category: 'Araçlar',
    icon: 'car-sport',
    iconType: 'Ionicons',
    color: '#EF4444',
    accentColor: '#FEE2E2',
  },
  {
    id: 'bicycle',
    name: 'Bisiklet',
    clue: 'Pedallarını çevirerek iki tekerlek üstünde dengede gittiğimiz araç',
    category: 'Araçlar',
    icon: 'bicycle',
    iconType: 'Ionicons',
    color: '#10B981',
    accentColor: '#D1FAE5',
  },
  {
    id: 'airplane',
    name: 'Uçak',
    clue: 'Bulutların arasından uçarak uzak şehirlere götüren dev kanatlı araç',
    category: 'Araçlar',
    icon: 'airplane',
    iconType: 'Ionicons',
    color: '#3B82F6',
    accentColor: '#DBEAFE',
  },
  {
    id: 'boat',
    name: 'Gemi',
    clue: 'Mavi denizlerin ve okyanusların üzerinde yüzen büyük taşıt',
    category: 'Araçlar',
    icon: 'boat',
    iconType: 'Ionicons',
    color: '#0284C7',
    accentColor: '#E0F2FE',
  },
  {
    id: 'rocket',
    name: 'Roket',
    clue: 'Uzaya, yıldızlara ve gezegenlere gitmek için fırlatılan araç',
    category: 'Araçlar',
    icon: 'rocket',
    iconType: 'Ionicons',
    color: '#8B5CF6',
    accentColor: '#EDE9FE',
  },

  // Eşyalar & Günlük Yaşam
  {
    id: 'clock',
    name: 'Saat',
    clue: 'Akrep ve yelkovanıyla zamanı ve dakikaları gösteren alet',
    category: 'Eşyalar',
    icon: 'time',
    iconType: 'Ionicons',
    color: '#6366F1',
    accentColor: '#EEF2FF',
  },
  {
    id: 'book',
    name: 'Kitap',
    clue: 'Sayfaları çevrilerek okunan, bilgi ve masal dolu eşya',
    category: 'Eşyalar',
    icon: 'book',
    iconType: 'Ionicons',
    color: '#14B8A6',
    accentColor: '#CCFBF1',
  },
  {
    id: 'guitar',
    name: 'Gitar',
    clue: 'Tellerine dokununca güzel müzik ve şarkı çalan enstrüman',
    category: 'Eşyalar',
    icon: 'musical-notes',
    iconType: 'Ionicons',
    color: '#F59E0B',
    accentColor: '#FEF3C7',
  },
  {
    id: 'lightbulb',
    name: 'Ampul',
    clue: 'Düğmeye basınca odayı aydınlatan ve yeni fikirleri simgeleyen eşya',
    category: 'Eşyalar',
    icon: 'bulb',
    iconType: 'Ionicons',
    color: '#EAB308',
    accentColor: '#FEF9C3',
  },
  {
    id: 'camera',
    name: 'Fotoğraf Makinesi',
    clue: 'Anıları ve güzel manzaraları ölümsüzleştirmek için çekim yapan alet',
    category: 'Eşyalar',
    icon: 'camera',
    iconType: 'Ionicons',
    color: '#64748B',
    accentColor: '#F1F5F9',
  },
  {
    id: 'glasses',
    name: 'Gözlük',
    clue: 'Yazın güneşten korunmak veya yazıları net görmek için göze takılan eşya',
    category: 'Eşyalar',
    icon: 'glasses',
    iconType: 'Ionicons',
    color: '#475569',
    accentColor: '#F8FAFC',
  },
];
