import { CameraQuest, QuestCategory } from '../types/game';
import { THEME } from '../../theme/theme';

// 1. Zengin, eğlenceli ve komik yüz mimikleri kütüphanesi
const FACE_QUESTS: CameraQuest[] = [
  {
    id: 'f-tongue-1',
    category: 'funny',
    title: 'Çılgın Şapşal Yüz',
    prompt: 'Dilini olabildiğince dışarı çıkar ve gözlerini hafif şaşı yap!',
    hint: 'En komik ve deli dolu yüz ifadenle kameraya bak.',
    emoji: '😜',
    levelRequired: 1,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 10,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.accent,
  },
  {
    id: 'f-shock-1',
    category: 'funny',
    title: 'Büyük Şok & Panik',
    prompt: 'Ağzını kocaman aç, gözlerini büyüt ve ellerini yanaklarına koy!',
    hint: 'Piyangodan 1 milyar TL çıkmış gibi şoke ol.',
    emoji: '😲',
    levelRequired: 1,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'f-smile-1',
    category: 'face',
    title: '32 Diş Gülümseme',
    prompt: 'Kameraya dön ve tüm dişlerini göstererek kahkaha atar gibi gül!',
    hint: 'Gözlerin kısılacak kadar içten ve mutlu gülümse.',
    emoji: '😁',
    levelRequired: 1,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 7,
    badgeText: 'Güleryüz',
    badgeColor: THEME.colors.mint,
  },
  {
    id: 'f-thinker-1',
    category: 'funny',
    title: 'Derin Düşünür Filozof',
    prompt: 'Çeneni eline yasla ve tavana doğru bilge bir filozof gibi bak!',
    hint: '"Hayatın anlamı nedir acaba?" der gibi derin ve bilge görün.',
    emoji: '🤔',
    levelRequired: 2,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 8,
    badgeText: 'Tiyatro Pozu',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'f-sleepy-1',
    category: 'funny',
    title: 'Uykucu Tembel',
    prompt: 'Gözlerini bayık yap ve kocaman esniyormuş gibi poz ver!',
    hint: 'Pazar sabahı saat 6\'da uyanmış gibi bitkin ve uykulu görün.',
    emoji: '🥱',
    levelRequired: 2,
    timeLimit: 24,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.accent,
  },
  {
    id: 'f-cat-1',
    category: 'funny',
    title: 'Şirin Kedi Surat',
    prompt: 'Yanaklarını şişir, dudaklarını büz ve masum kedi gibi bak!',
    hint: 'Annenden en sevdiğin tatlıyı isterken yaptığın o tatlı yüz!',
    emoji: '🐱',
    levelRequired: 2,
    timeLimit: 24,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'f-robot-1',
    category: 'funny',
    title: 'Duygusuz Robot',
    prompt: 'Hiçbir mimik yapmadan, gözlerini kırpmadan dik dik bak!',
    hint: 'Sıfır duygu, taş gibi sert ve robotik bir surat.',
    emoji: '🤖',
    levelRequired: 3,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 10,
    badgeText: 'Usta Poz',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 'f-duck-1',
    category: 'funny',
    title: 'Ördek Dudak (Duck Face)',
    prompt: 'Dudaklarını öne doğru iyice uzatarak klasik ördek pozu ver!',
    hint: 'En abartılı moda fotoğrafı pozu gibi dudaklarını büz.',
    emoji: '🦆',
    levelRequired: 2,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 8,
    badgeText: 'Popüler Poz',
    badgeColor: THEME.colors.accent,
  },
  {
    id: 'f-angry-1',
    category: 'funny',
    title: 'Öfkeli Boğa',
    prompt: 'Kaşlarını olabildiğince çat ve kameraya en sert bakışını at!',
    hint: 'En sevdiğin çikolatayı biri yemiş gibi sinirli görün.',
    emoji: '😠',
    levelRequired: 2,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 8,
    badgeText: 'Tiyatro Pozu',
    badgeColor: THEME.colors.error,
  },
  {
    id: 'f-detective-1',
    category: 'funny',
    title: 'Şüpheci Dedektif',
    prompt: 'Tek gözünü kıs, başını hafifçe yana eğ ve şüpheyle bak!',
    hint: '"Seni bir yerden gözüm ısırıyor ama nereden?" bakışı.',
    emoji: '🧐',
    levelRequired: 3,
    timeLimit: 24,
    isFaceQuest: true,
    funFactor: 8,
    badgeText: 'Gizemli Poz',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'f-freeze-1',
    category: 'funny',
    title: 'Kutup Ayazı (Donmuş Yüz)',
    prompt: 'Dişlerini sık, titriyormuş gibi yap ve soğuktan donmuş gibi bak!',
    hint: 'Erzurum ayazında montsuz kalmış gibi büzüş.',
    emoji: '🥶',
    levelRequired: 3,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.sky,
  },
  {
    id: 'f-sour-1',
    category: 'funny',
    title: 'Ekşi Limon Sürprizi',
    prompt: 'Aşırı ekşi bir limon yemiş gibi tüm yüzünü buruştur!',
    hint: 'Gözlerini, burnunu ve ağzını merkeze doğru topla.',
    emoji: '🍋',
    levelRequired: 3,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 10,
    badgeText: 'Ekşi Surat',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'f-mindblown-1',
    category: 'funny',
    title: 'Beyni Yanan İnsan',
    prompt: 'Gözlerini sonuna kadar aç, ağzını arala ve ellerini başına vur!',
    hint: 'Matematik sınavının son sorusunu görünce gelen aydınlanma!',
    emoji: '🤯',
    levelRequired: 4,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Büyük Şaşkınlık',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 'f-superhero-1',
    category: 'face',
    title: 'Cesur Süper Kahraman',
    prompt: 'Çeneni yukarı kaldır, gözlerini ufka dik ve kararlı bak!',
    hint: 'Dünyayı kurtarmaya hazır bir kahraman edasıyla poz ver.',
    emoji: '🦸',
    levelRequired: 3,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 7,
    badgeText: 'Kahraman Pozu',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'f-winking-1',
    category: 'face',
    title: 'Havalı Göz Kırpma',
    prompt: 'Kameraya dön, tek gözünü tatlıca kırp ve gülümse!',
    hint: 'Film yıldızı gibi karizmatik ve neşeli bir göz kırpışı.',
    emoji: '😉',
    levelRequired: 2,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 7,
    badgeText: 'Karizma',
    badgeColor: THEME.colors.accent,
  },
  {
    id: 'f-rockstar-1',
    category: 'funny',
    title: 'Rock Yıldızı Çığlığı',
    prompt: 'Ağzını kocaman açarak stadyumda şarkı söylüyormuş gibi haykır!',
    hint: 'Gitar solosu atan bir rock yıldızı gibi enerji patlaması yaşa.',
    emoji: '🎸',
    levelRequired: 4,
    timeLimit: 20,
    isFaceQuest: true,
    funFactor: 10,
    badgeText: 'Çılgın Poz',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'f-innocent-1',
    category: 'face',
    title: 'Masum Yavru Köpek Bakışı',
    prompt: 'Gözlerini kocaman yapıp aşağıdan yukarıya doğru mahzun bak!',
    hint: 'Kimsenin sana hayır diyemeyeceği o en masum bakış.',
    emoji: '🥺',
    levelRequired: 2,
    timeLimit: 24,
    isFaceQuest: true,
    funFactor: 8,
    badgeText: 'Masum Yüz',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'f-sneaky-1',
    category: 'funny',
    title: 'Sinsi Kötü Adam Gülüşü',
    prompt: 'Tek kaşını hafifçe kaldır ve sinsi sinsi kıs kıs gül!',
    hint: '"Planım tıkır tıkır işliyor muahahah" bakışı.',
    emoji: '🦹',
    levelRequired: 4,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Sinsi Poz',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 'f-sleeping-1',
    category: 'face',
    title: 'Huzurlu Uyku',
    prompt: 'Gözlerini kapat, başını hafifçe yana yatır ve mışıl mışıl uyu!',
    hint: 'Pofuduk yastığında rüya görüyormuş gibi sakinleş.',
    emoji: '😴',
    levelRequired: 1,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 6,
    badgeText: 'Huzurlu Yüz',
    badgeColor: THEME.colors.sky,
  },
  {
    id: 'f-wide-eyes-1',
    category: 'funny',
    title: 'Faltaşı Gözler',
    prompt: 'Gözlerini olabildiğince aç, kaşlarını kaldır ve donup kal!',
    hint: 'Araba farı görmüş tavşan gibi kocaman açılmış gözler.',
    emoji: '👀',
    levelRequired: 2,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 8,
    badgeText: 'Büyük Gözler',
    badgeColor: THEME.colors.accent,
  },
];

// 2. Canlı ve zengin renk avı görevleri
const COLOR_QUESTS: CameraQuest[] = [
  {
    id: 'c-red-1',
    category: 'color',
    title: 'Kırmızı Alarm!',
    prompt: 'Etrafında canlı kırmızı renkte bir eşya bul ve fotoğrafını çek!',
    hint: 'Kupa, tişört, elma, kalem veya kırmızı bir ambalaj olabilir.',
    emoji: '🔴',
    levelRequired: 1,
    timeLimit: 30,
    targetColor: 'red',
    badgeText: 'Kırmızı Avı',
    badgeColor: THEME.colors.error,
  },
  {
    id: 'c-blue-1',
    category: 'color',
    title: 'Mavi Okyanus',
    prompt: 'Odanda mavi renkli belirgin bir nesneyi kadraja al!',
    hint: 'Kot pantolon, su şişesi, defter kapağı veya mavi bir yastık.',
    emoji: '🔵',
    levelRequired: 1,
    timeLimit: 30,
    targetColor: 'blue',
    badgeText: 'Mavi Avı',
    badgeColor: THEME.colors.sky,
  },
  {
    id: 'c-green-1',
    category: 'color',
    title: 'Doğanın Yeşili',
    prompt: 'Yeşil bir yaprak, saksı bitkisi veya yeşil bir eşya bul!',
    hint: 'Canlı yeşil tonları içeren herhangi bir cisim geçerlidir.',
    emoji: '🟢',
    levelRequired: 1,
    timeLimit: 30,
    targetColor: 'green',
    badgeText: 'Yeşil Avı',
    badgeColor: THEME.colors.mint,
  },
  {
    id: 'c-yellow-1',
    category: 'color',
    title: 'Güneş Sarısı',
    prompt: 'Sarı veya altın sarısı renkte bir eşyayı kadraja al!',
    hint: 'Muz, sarı ambalaj, post-it veya sarı tişört harika olur.',
    emoji: '🟡',
    levelRequired: 2,
    timeLimit: 28,
    targetColor: 'yellow',
    badgeText: 'Sarı Avı',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'c-orange-1',
    category: 'color',
    title: 'Tatlı Portakal Turuncusu',
    prompt: 'Turuncu renkte bir nesne veya ambalaj bulup fotoğrafla!',
    hint: 'Portakal, mandalina, turuncu kalem veya kupa.',
    emoji: '🟠',
    levelRequired: 2,
    timeLimit: 28,
    targetColor: 'orange',
    badgeText: 'Turuncu Avı',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 'c-purple-1',
    category: 'color',
    title: 'Asil Mor & Lavanta',
    prompt: 'Mor veya lavanta renginde bir nesneyi kameraya göster!',
    hint: 'Mor kıyafet, kitap ayracı, çiçek veya oyuncak.',
    emoji: '🟣',
    levelRequired: 3,
    timeLimit: 26,
    targetColor: 'purple',
    badgeText: 'Mor Avı',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'c-white-1',
    category: 'color',
    title: 'Bembeyaz Sayfa',
    prompt: 'Bembeyaz bir A4 kağıdı, peçete veya beyaz bir eşya çek!',
    hint: 'Göz alıcı temizlikte beyaz bir yüzey yakala.',
    emoji: '⚪',
    levelRequired: 1,
    timeLimit: 30,
    targetColor: 'white',
    badgeText: 'Beyaz Avı',
    badgeColor: '#64748B',
  },
  {
    id: 'c-dark-1',
    category: 'color',
    title: 'Karanlığın Gücü (Siyah)',
    prompt: 'Koyu siyah bir nesne veya ekranı kadraja doldur!',
    hint: 'Kapalı monitör, siyah ceket veya siyah bir defter.',
    emoji: '⚫',
    levelRequired: 2,
    timeLimit: 28,
    targetColor: 'dark',
    badgeText: 'Siyah Avı',
    badgeColor: '#1E293B',
  },
];

// 3. Ev, Oda, Mutfak ve Çalışma Masası Eşyaları
const OBJECT_QUESTS: CameraQuest[] = [
  {
    id: 'o-cup-1',
    category: 'object',
    title: 'Kahve & Çay Kupası',
    prompt: 'Bir kupa, su bardağı veya matarayı yakından çek!',
    hint: 'Masanın üstündeki kupa veya mutfaktan bir bardak.',
    emoji: '☕',
    levelRequired: 1,
    timeLimit: 30,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 'o-bottle-1',
    category: 'object',
    title: 'Su Şişesi & Matara',
    prompt: 'Bir su şişesi veya termos bulup kameraya göster!',
    hint: 'Mavi, şeffaf veya renkli su şişesini yakala.',
    emoji: '🍶',
    levelRequired: 1,
    timeLimit: 28,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.sky,
  },
  {
    id: 'o-shoe-1',
    category: 'object',
    title: 'Günün Ayakkabısı',
    prompt: 'Bir spor ayakkabı, terlik veya botu fotoğrafla!',
    hint: 'Kapı önündeki veya ayağındaki ayakkabıyı çek.',
    emoji: '👟',
    levelRequired: 2,
    timeLimit: 26,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'o-cutlery-1',
    category: 'object',
    title: 'Çatal veya Kaşık',
    prompt: 'Mutfaktan bir çatal, kaşık veya bıçak bulup kadraja al!',
    hint: 'Parlak metal veya plastik çatal kaşığı yakala.',
    emoji: '🍴',
    levelRequired: 2,
    timeLimit: 26,
    badgeText: 'Mutfak Avı',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'o-screen-1',
    category: 'object',
    title: 'Aydınlık Ekran',
    prompt: 'Bir bilgisayar, televizyon veya tablet ekranını çek!',
    hint: 'Işık saçan dijital ekranı kadraja sığdır.',
    emoji: '💻',
    levelRequired: 2,
    timeLimit: 28,
    badgeText: 'Teknoloji',
    badgeColor: THEME.colors.sky,
  },
  {
    id: 'o-mouse-1',
    category: 'object',
    title: 'Bilgisayar Faresi (Mouse)',
    prompt: 'Masanın üstündeki mouse veya klavyeyi yakından çek!',
    hint: 'Bilgisayar faresi veya tuş takımını kadraja al.',
    emoji: '🖱️',
    levelRequired: 3,
    timeLimit: 24,
    badgeText: 'Teknoloji',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'o-glasses-1',
    category: 'object',
    title: 'Gözlük Dedektifi',
    prompt: 'Bir güneş gözlüğü veya numaralı gözlük bul ve çek!',
    hint: 'Masanın üstündeki veya birinin taktığı gözlük.',
    emoji: '👓',
    levelRequired: 3,
    timeLimit: 25,
    badgeText: 'Aksesuar',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 'o-clock-1',
    category: 'object',
    title: 'Zaman Akıyor (Saat)',
    prompt: 'Kolda taşınan bir saat veya duvardaki saati fotoğrafla!',
    hint: 'Kadranı veya dijital ekranı olan herhangi bir saat.',
    emoji: '⌚',
    levelRequired: 3,
    timeLimit: 26,
    badgeText: 'Zaman Avı',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'o-plant-1',
    category: 'object',
    title: 'Saksıdaki Dost (Bitki)',
    prompt: 'Evin içindeki veya penceredeki canlı bir saksı bitkisini çek!',
    hint: 'Yeşil yaprakları olan sevimli bir ev bitkisi.',
    emoji: '🪴',
    levelRequired: 2,
    timeLimit: 28,
    badgeText: 'Doğa Avı',
    badgeColor: THEME.colors.mint,
  },
  {
    id: 'o-key-1',
    category: 'object',
    title: 'Gizli Anahtar',
    prompt: 'Bir ev anahtarı veya araba anahtarlığı bulup göster!',
    hint: 'Cebinden veya masadan anahtarlığını yakala.',
    emoji: '🔑',
    levelRequired: 3,
    timeLimit: 25,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'o-lamp-1',
    category: 'object',
    title: 'Açık Lamba & Işık',
    prompt: 'Yanan bir masa lambası veya ampulün ışığını kadraja al!',
    hint: 'Işık saçan aydınlık bir lambayı çek.',
    emoji: '💡',
    levelRequired: 2,
    timeLimit: 26,
    badgeText: 'Işık Avı',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'o-cushion-1',
    category: 'object',
    title: 'Pofuduk Yastık',
    prompt: 'Koltukta duran bir yastık veya minderi fotoğrafla!',
    hint: 'Yumuşak, renkli veya desenli bir yastık.',
    emoji: '🛋️',
    levelRequired: 2,
    timeLimit: 28,
    badgeText: 'Ev Eşyası',
    badgeColor: THEME.colors.accent,
  },
  {
    id: 'o-headphones-1',
    category: 'object',
    title: 'Müzik Kulaklığı',
    prompt: 'Büyük bir kafa üstü kulaklık veya kablosuz kulaklık çek!',
    hint: 'Müzik dinlediğin kulaklığı kadraja göster.',
    emoji: '🎧',
    levelRequired: 3,
    timeLimit: 25,
    badgeText: 'Teknoloji',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'o-charger-1',
    category: 'object',
    title: 'Şarj Kablosu',
    prompt: 'Bir telefon şarj kablosu veya adaptörünü göster!',
    hint: 'Masanın üstündeki beyaz veya siyah şarj kablosu.',
    emoji: '🔌',
    levelRequired: 3,
    timeLimit: 25,
    badgeText: 'Teknoloji',
    badgeColor: THEME.colors.sky,
  },
  {
    id: 'o-remote-1',
    category: 'object',
    title: 'TV Kumandası',
    prompt: 'Televizyon veya klima kumandasını kadraja al!',
    hint: 'Üzerinde tuşları olan kumandayı fotoğrafla.',
    emoji: '📺',
    levelRequired: 2,
    timeLimit: 26,
    badgeText: 'Ev Eşyası',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 'o-backpack-1',
    category: 'object',
    title: 'Sırt Çantası',
    prompt: 'Bir okul çantası veya el çantasını fotoğrafla!',
    hint: 'Fermuarlı bir sırt veya omuz çantası.',
    emoji: '🎒',
    levelRequired: 2,
    timeLimit: 28,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'o-fruit-1',
    category: 'object',
    title: 'Taze Meyve',
    prompt: 'Elma, muz, mandalina veya herhangi bir meyve bul!',
    hint: 'Mutfaktan lezzetli bir meyveyi kadraja getir.',
    emoji: '🍎',
    levelRequired: 2,
    timeLimit: 28,
    badgeText: 'Mutfak Avı',
    badgeColor: THEME.colors.error,
  },
  {
    id: 'o-sock-1',
    category: 'object',
    title: 'Renkli Çorap',
    prompt: 'Ayağındaki veya çekmecendeki bir çorabı fotoğrafla!',
    hint: 'Desenli veya tek renk bir çorap karesi.',
    emoji: '🧦',
    levelRequired: 2,
    timeLimit: 26,
    badgeText: 'Giyim',
    badgeColor: THEME.colors.accent,
  },
];

// 4. Geometrik Şekiller ve Formlar
const SHAPE_QUESTS: CameraQuest[] = [
  {
    id: 's-rect-1',
    category: 'shape',
    title: 'Dört Köşe Kitap',
    prompt: 'Dört kenarı düzgün bir kitap veya defter bul ve çek!',
    hint: 'Dikdörtgen veya kare formundaki bir cilt.',
    emoji: '📚',
    levelRequired: 1,
    timeLimit: 30,
    badgeText: 'Şekil Avı',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 's-circle-1',
    category: 'shape',
    title: 'Kusursuz Çember',
    prompt: 'Tamamen yuvarlak bir tabak, bardak altlığı veya kapak bul!',
    hint: 'Köşesi olmayan pürüzsüz dairesel bir form çek.',
    emoji: '⚪',
    levelRequired: 2,
    timeLimit: 28,
    badgeText: 'Şekil Avı',
    badgeColor: THEME.colors.mint,
  },
  {
    id: 's-box-1',
    category: 'shape',
    title: 'Kare Kutu',
    prompt: 'Kargo kutusu, ayakkabı kutusu veya kare bir ambalaj bul!',
    hint: 'Küp veya kutu şeklinde köşeli bir nesne.',
    emoji: '📦',
    levelRequired: 2,
    timeLimit: 28,
    badgeText: 'Şekil Avı',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 's-long-1',
    category: 'shape',
    title: 'Uzun İnce Çubuk (Kalem)',
    prompt: 'Bir tükenmez kalem, kurşun kalem veya fırça göster!',
    hint: 'Uzun ve silindirik bir kırtasiye aleti.',
    emoji: '✏️',
    levelRequired: 1,
    timeLimit: 30,
    badgeText: 'Şekil Avı',
    badgeColor: THEME.colors.yellow,
  },
];

// Tüm temel görevleri birleştir
export const QUEST_POOL: CameraQuest[] = [
  ...FACE_QUESTS,
  ...COLOR_QUESTS,
  ...OBJECT_QUESTS,
  ...SHAPE_QUESTS,
];

// 5. PROCEDURAL QUEST GENERATOR (50x Soru Havuzu Üreticisi)
// Binlerce benzersiz dinamik görev üreten sonsuz soru motoru
const PROCEDURAL_COLORS = [
  { name: 'Kırmızı', hex: 'red', emoji: '🔴' },
  { name: 'Mavi', hex: 'blue', emoji: '🔵' },
  { name: 'Yeşil', hex: 'green', emoji: '🟢' },
  { name: 'Sarı', hex: 'yellow', emoji: '🟡' },
  { name: 'Turuncu', hex: 'orange', emoji: '🟠' },
  { name: 'Mor', hex: 'purple', emoji: '🟣' },
  { name: 'Beyaz', hex: 'white', emoji: '⚪' },
  { name: 'Siyah', hex: 'dark', emoji: '⚫' },
];

const PROCEDURAL_OBJECTS = [
  'bir giysi veya tişört',
  'bir bardak veya kupa',
  'bir kalem veya yazı gereci',
  'bir defter kapağı veya kağıt',
  'bir ambalaj veya kutu',
  'bir yastık veya minder',
  'bir ayakkabı veya terlik',
  'bir mutfak eşyası',
  'bir elektronik cihaz',
];

const PROCEDURAL_FUNNY_ACTIONS = [
  { action: 'Sol gözünü kırpıp sağ yanağını şişirerek poz ver!', emoji: '😜' },
  { action: 'İki elinle bıyık yapıp en havalı casus gibi bak!', emoji: '🕵️' },
  { action: 'Kafanı sağa yatır, dilini hafif çıkar ve şaşı bak!', emoji: '🤪' },
  { action: 'Kollarına sarıl, soğuktan donmuş gibi dişlerini takırdat!', emoji: '🥶' },
  { action: 'Zafer işareti (V) yapıp kocaman gülümse!', emoji: '✌️' },
  { action: 'Parmağınla kamerayı göster ve "Seni yakaladım!" pozu ver!', emoji: '👉' },
  { action: 'Ağzını "O" şeklinde açıp şaşkın balık gibi bak!', emoji: '🐟' },
  { action: 'Gözlerini devirerek "Aman ne komik" pozu ver!', emoji: '🙄' },
  { action: 'Gizli ajan gibi ceketinin yakasını tutarak yandan bak!', emoji: '🕶️' },
  { action: 'Gülmekten karnına ağrılar girmiş gibi gözlerini kıs!', emoji: '🤣' },
];

export function generateProceduralQuest(seed: number): CameraQuest {
  const type = seed % 3;

  if (type === 0) {
    // Dinamik Renk + Nesne Kombinasyonu (8 Renk x 9 Nesne = 72 Çeşit)
    const color = PROCEDURAL_COLORS[seed % PROCEDURAL_COLORS.length];
    const obj = PROCEDURAL_OBJECTS[(seed * 7) % PROCEDURAL_OBJECTS.length];
    return {
      id: `proc-col-${seed}`,
      category: 'color',
      title: `${color.name} Avı!`,
      prompt: `Etrafında ${color.name.toLowerCase()} renkte ${obj} bul ve çek!`,
      hint: `${color.name} tonlarının belirgin olduğu nesneyi kadraja yaklaştır.`,
      emoji: color.emoji,
      levelRequired: Math.min(5, Math.floor(seed / 10) + 1),
      timeLimit: 26,
      targetColor: color.hex as any,
      badgeText: `${color.name} Avı`,
      badgeColor: THEME.colors.primary,
    };
  } else if (type === 1) {
    // Dinamik Komik Yüz Görevi (10 Farklı Tiyatro Aksiyonu)
    const funny = PROCEDURAL_FUNNY_ACTIONS[seed % PROCEDURAL_FUNNY_ACTIONS.length];
    return {
      id: `proc-fun-${seed}`,
      category: 'funny',
      title: 'Çılgın Görev!',
      prompt: funny.action,
      hint: 'Mimiğini abartmaktan çekinme, jüri cesur pozları sever!',
      emoji: funny.emoji,
      levelRequired: Math.min(5, Math.floor(seed / 10) + 1),
      timeLimit: 24,
      isFaceQuest: true,
      funFactor: 9,
      badgeText: 'Sürpriz Poz',
      badgeColor: THEME.colors.accent,
    };
  } else {
    // Sabit havuzdan dengeli seçim
    const q = QUEST_POOL[seed % QUEST_POOL.length];
    return {
      ...q,
      id: `pool-${seed}-${q.id}`,
    };
  }
}
