import { CameraQuest } from '../types/game';
import { THEME } from '../../theme/theme';

export const QUEST_POOL: CameraQuest[] = [
  // --- SEVİYE 1: Kolay Başlangıç (Canlı Renkler & İlk Yüz İfadesi) ---
  {
    id: 'c-red-1',
    category: 'color',
    title: 'Kırmızı Alarm!',
    prompt: 'Etrafında kırmızı renkte bir eşya bul ve fotoğrafını çek!',
    hint: 'Kupa, tişört, elma, kalem veya kırmızı bir ambalaj olabilir.',
    emoji: '🔴',
    levelRequired: 1,
    timeLimit: 30,
    targetColor: 'red',
    badgeText: 'Renk Avı',
    badgeColor: THEME.colors.error,
  },
  {
    id: 'f-smile-1',
    category: 'face',
    title: 'Büyük Gülümseme!',
    prompt: 'Kameraya dön ve 32 diş kocaman, neşeli bir gülümseme ver!',
    hint: 'Gözlerin kısılacak kadar içten ve mutlu gülümse.',
    emoji: '😁',
    levelRequired: 1,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 7,
    badgeText: 'Yüz İfadesi',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'c-blue-1',
    category: 'color',
    title: 'Mavi Dünyası',
    prompt: 'Odanda mavi renkli herhangi bir nesneyi yakala!',
    hint: 'Kot pantolon, su şişesi, defter kapağı veya mavi bir yastık.',
    emoji: '🔵',
    levelRequired: 1,
    timeLimit: 30,
    targetColor: 'blue',
    badgeText: 'Renk Avı',
    badgeColor: THEME.colors.sky,
  },
  {
    id: 'o-cup-1',
    category: 'object',
    title: 'Kahve & Çay Molası',
    prompt: 'Bir kupa, bardak veya su şişesi bulup fotoğrafla!',
    hint: 'Mutfaktan ya da masanın üstünden bir içecek bardağı yakala.',
    emoji: '☕',
    levelRequired: 1,
    timeLimit: 30,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.secondary,
  },

  // --- SEVİYE 2: Komik Durumlar & Şekiller ---
  {
    id: 'f-tongue-1',
    category: 'funny',
    title: 'Çılgın Şapşal Yüz!',
    prompt: 'Dilini dışarı çıkar ve gözlerini hafif şaşı yaparak poz ver!',
    hint: 'En komik ve deli dolu yüz ifadenle kameraya bak.',
    emoji: '😜',
    levelRequired: 2,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 10,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.accent,
  },
  {
    id: 's-rect-1',
    category: 'shape',
    title: 'Dört Köşe!',
    prompt: 'Dört kenarı olan bir kitap, defter veya kutu bul!',
    hint: 'Dikdörtgen veya kare şeklinde düzgün kenarlı bir nesne çek.',
    emoji: '📚',
    levelRequired: 2,
    timeLimit: 28,
    badgeText: 'Şekil Avı',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'c-green-1',
    category: 'color',
    title: 'Doğanın Yeşili',
    prompt: 'Yeşil bir yaprak, saksı bitkisi veya yeşil bir eşya bul!',
    hint: 'Canlı yeşil tonları içeren herhangi bir cisim geçerlidir.',
    emoji: '🌿',
    levelRequired: 2,
    timeLimit: 28,
    targetColor: 'green',
    badgeText: 'Renk Avı',
    badgeColor: THEME.colors.mint,
  },
  {
    id: 'f-shock-1',
    category: 'funny',
    title: 'Büyük Şok!',
    prompt: 'Ağzını kocaman aç, gözlerini büyüt ve ellerini yanaklarına koy!',
    hint: 'Piyangodan 1 milyar TL çıkmış gibi şoke ol.',
    emoji: '😲',
    levelRequired: 2,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.yellow,
  },

  // --- SEVİYE 3: Orta Seviye & Çevre Nesneleri ---
  {
    id: 'c-yellow-1',
    category: 'color',
    title: 'Güneş Işıltısı',
    prompt: 'Sarı veya altın sarısı renkte bir eşyayı kadraja al!',
    hint: 'Muz, sarı ambalaj, post-it veya sarı tişört harika olur.',
    emoji: '🟡',
    levelRequired: 3,
    timeLimit: 25,
    targetColor: 'yellow',
    badgeText: 'Renk Avı',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'f-thinker-1',
    category: 'funny',
    title: 'Derin Düşünür',
    prompt: 'Çeneni eline yasla ve tavana doğru filozof gibi bak!',
    hint: '"Hayatın anlamı nedir acaba?" der gibi derin ve bilge görün.',
    emoji: '🤔',
    levelRequired: 3,
    timeLimit: 25,
    isFaceQuest: true,
    funFactor: 8,
    badgeText: 'Tiyatro Pozu',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'o-screen-1',
    category: 'object',
    title: 'Dijital Dünya',
    prompt: 'Bir bilgisayar, televizyon veya tablet ekranını çek!',
    hint: 'Ekrandaki ışık ve pikselleri kadraja sığdır.',
    emoji: '💻',
    levelRequired: 3,
    timeLimit: 26,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.sky,
  },
  {
    id: 'o-shoe-1',
    category: 'object',
    title: 'Yolculuk Başlasın',
    prompt: 'Bir ayakkabı, terlik veya çorap bul ve fotoğrafla!',
    hint: 'Kapının önünden veya ayağından hızlıca bir kare yakala.',
    emoji: '👟',
    levelRequired: 3,
    timeLimit: 26,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.secondary,
  },

  // --- SEVİYE 4+: Zorlayıcı & Ultra Komik Pozlar ---
  {
    id: 'f-sleepy-1',
    category: 'funny',
    title: 'Uykucu Tembel!',
    prompt: 'Gözlerini bayık yap ve kocaman esniyormuş gibi poz ver!',
    hint: 'Pazar sabahı saat 6\'da uyanmış gibi bitkin ve uykulu görün.',
    emoji: '🥱',
    levelRequired: 4,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.accent,
  },
  {
    id: 'o-cutlery-1',
    category: 'object',
    title: 'Mutfak Dedektifi',
    prompt: 'Bir çatal veya kaşık bulup kameraya göster!',
    hint: 'Parlak metal veya plastik mutfak aletini kadraja al.',
    emoji: '🍴',
    levelRequired: 4,
    timeLimit: 24,
    badgeText: 'Eşya Avı',
    badgeColor: THEME.colors.primary,
  },
  {
    id: 'f-cat-1',
    category: 'funny',
    title: 'Şirin Kedi Bakışı',
    prompt: 'Yanaklarını şişir, gözlerini büyüt ve masum kedi gibi bak!',
    hint: 'Annenden harçlık isterken yaptığın o tatlı yüz ifadesi!',
    emoji: '🐱',
    levelRequired: 4,
    timeLimit: 22,
    isFaceQuest: true,
    funFactor: 9,
    badgeText: 'Komik Poz',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'o-light-1',
    category: 'object',
    title: 'Aydınlık Anlar',
    prompt: 'Açık olan bir lamba, ampul veya fener ışığı yakala!',
    hint: 'Karanlığı aydınlatan parıltılı bir ışık kaynağı çek.',
    emoji: '💡',
    levelRequired: 4,
    timeLimit: 22,
    badgeText: 'Zor Görev',
    badgeColor: THEME.colors.yellow,
  },
  {
    id: 'f-robot-1',
    category: 'funny',
    title: 'Duygusuz Robot',
    prompt: 'Hiçbir mimik yapmadan, gözlerini kırpmadan dik dik bak!',
    hint: 'Sıfır duygu, taş gibi sert ve robotik bir surat.',
    emoji: '🤖',
    levelRequired: 5,
    timeLimit: 20,
    isFaceQuest: true,
    funFactor: 10,
    badgeText: 'Usta Poz',
    badgeColor: THEME.colors.secondary,
  },
  {
    id: 's-circle-1',
    category: 'shape',
    title: 'Mükemmel Çember',
    prompt: 'Tamamen yuvarlak bir tabak, kapak veya saat bul!',
    hint: 'Köşesi olmayan kusursuz bir dairesel form çek.',
    emoji: '⚪',
    levelRequired: 5,
    timeLimit: 22,
    badgeText: 'Şekil Avı',
    badgeColor: THEME.colors.primary,
  },
];
